sonar.projectKey=solventa-frontend
sonar.projectName=Solventa Frontend
sonar.sources=apps/web/src
sonar.tests=apps/web/tests,e2e/cypress
sonar.exclusions=apps/web/src/graphql/tipos.ts,apps/web/public/**,**/node_modules/**
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
